---
- hosts: app_nodes
  become: yes
  vars:
  	JRE_RPM_URL: https://corretto.aws/downloads/latest/amazon-coretto-11-x64-al2-jre.rpm
  	APP_JAR_URL: https://github.com/jkanclerz/pp5-voucherstore-11/releases/download/v0.1.1/application.jar
  	APP_DIR: opt/ecommerce
  	APP_USER: ecommerce
  tasks: 
  	- name: "install java jre"
  	  yum:
  	  	name: "{{  JRE_RPM_ URL }}"
  	  	state: present
   - name: "ensure dest dir present" 
     file: 
     	path: "{{ APP_DIR }}"
     	state: directory
   - name: "download app"
     get_url: 
     	url: "{{ APP_JAR_URL }}"
     	dest: "{{ APP_DIR ~ '/application.jar' }}"
   - name: "create usr"
     user: 
     	name: "{{ APP_USER }}"
   - name: "place service cfg"
     template: 
     	src: files/ecommerce.service
     	dest: /etc/systemd/system/ecommerce.service
    - name: 
      systemd: 
        name: ecommerce
        daemon_reload: yes
        enabled: yes
        state: restarted 
        
- hosts: lb_nodes
  become: yes
  vars: 
    epel_rpm_url: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    app_node_ips: 
      - 173.32.1.118
      - 173.32.9.122
  tasks: 
    - name: "install epel repo" 
      yum:
        name: "{{ epel_rpm_url }}"
    - name: "install epel repo"
      yum:
        name: nginx
    - name: "put nginx cfg"
      template: 
        src: files/ecommerce.conf
        dest: /etc/nginx/conf.d/ecommerce.conf
    - name: "restart nginx + during boot"
      systemd:
        name: nginx
        enabled: yes
        state: restarted    